### PR TITLE
Modal expansion: added KL, RBF and Modal Coefficients, hopefully without break everything

### PR DESCRIPTION
**Pull request by imapeartree**

### CODE REVIEW

**Review by lbusoni — CHANGES_REQUESTED** [review]
Some comments:

0. Use snake_case over CamelCase. Whenever possible, we should stick to this convention as described in code_convention.py. 
1. Scratch notebook are not needed. Either convert them into working examples with good documentation (using text cells) or delete them if they are for debugging purposes. 
2. I don't see why CircularMask should overload as_masked_array. Isn't the original method from BaseMask good enough? 
3. ZernikeCoefficients should derive from ModalCoefficients, not the opposite. What is the difference between the 2 classes?
5. Rename KLGenerator into KarhunenLoeveGenerator  
6. ModalDecomposer does too many things: and I'm pretty sure @cache is broken (or at least in danger) as you reassign self.mask. Is there a reason to have a single class adapting to different modal basis? 
- Let's have a ZernikeModalDecomposer that is an alias of ModalDecomposer. 
- Warn a deprecation when ModalDecompose is used instead of ZernikeModalDecomposer
- Create a KarhunenLoeveModalDecomposer 
- Create a RadialBasisFunctionModalDecomposer.
- In the future we can decide to re-use the symbol ModalDecomposer to act like a proxy to the various classes
7. Rename RBFGenerator into RadialBasisFunctionGenerator
8. Most of the tests of the new functions only test the shape or the size of the result. Is this enough?

**Comment by alfiopuglisi** [comment]
If I understand correctly, the idea is to generalize the ModalDecomposer class to allow different modal bases (Zernikes, KL, etc). The idea is sound, but it looks to me like the implementation is done backwards: there should be a generic ModalDecomposer class with the interface, and then either:
- (inheritance) derive classes like ZernikeModalDecomposer, KarhunenLoeveModalDecomposer, etc implementing the details; or
- (composition) instantiate the desired mode generator (e.g. ZernikeModeGenerator) and use it to initialize the generic ModalDecomposer.

I prefer the composition approach, and the generator classes are already there it seems.

**Comment by alfiopuglisi** [comment]
Reorganized ModalDecomposer to have a base class BaseModalDecomposer with all the rec. generating and projection code, independent from the modal base, and a series of generators for Zernike, KL and RBF modes.
Small classes ZernikeModalDecomposer, KLModalDecomposer and RFBModalDecomposer are very small classes derived from BaseModalDecomposer and only adding the modal generator instantiation.

The old ModalDecomposer has been kept without any interface changes, for backward compatibility.

**Comment by alfiopuglisi** [comment]
@lbusoni please review (your requested changes are blocking the pull request)

**Review by g-carla — CHANGES_REQUESTED** [review]
Tests in radial_basis_decomposer.py should be moved into the test folder.

**Review by g-carla — APPROVED** [review]

**Pull request merged**
